#!/bin/bash
set -e

psql -U "$DATABASE_USERNAME" -d "$DATABASE_NAME" -c "CREATE DATABASE $DEVELOPMENT_DATABASE_NAME;"
psql -U "$DATABASE_USERNAME" -d "$DATABASE_NAME" -c "CREATE DATABASE $TEST_DATABASE_NAME;"
